wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.22
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.5
    t:
      1:
      - 5
      4: 3.7.5
      5: 0.10.22
      8:
      - 5
activation:
  desc: null
  value: sigmoid
batch_size:
  desc: null
  value: 64
epochs:
  desc: null
  value: 10
l_rate:
  desc: null
  value: 0.001
optimizer:
  desc: null
  value: sgd
