wandb_version: 1

Cell_Type:
  value: GRU
batch_size:
  value: 32
beam_size:
  value: 10
dropout:
  value: 0
embedding_size:
  value: 32
epochs:
  value: 10
hidden_layer_size:
  value: 32
n_enc_dec_layers:
  value: 3
optimizer:
  value: Adam
