wandb_version: 1

Cell_Type:
  value: LSTM
batch_size:
  value: 64
beam_size:
  value: 1
dropout:
  value: 0
embedding_size:
  value: 16
epochs:
  value: 5
hidden_layer_size:
  value: 128
l_rate:
  value: 0.01
n_enc_dec_layers:
  value: 2
optimizer:
  value: Adam
