wandb_version: 1

Cell_Type:
  value: GRU
batch_size:
  value: 64
beam_size:
  value: 5
dropout:
  value: 0.2
embedding_size:
  value: 16
epochs:
  value: 10
hidden_layer_size:
  value: 128
l_rate:
  value: 0.01
n_enc_dec_layers:
  value: 2
optimizer:
  value: Nadam
