wandb_version: 1

Cell_Type:
  value: GRU
batch_size:
  value: 32
beam_size:
  value: 10
dropout:
  value: 0
embedding_size:
  value: 64
epochs:
  value: 5
hidden_layer_size:
  value: 128
l_rate:
  value: 0.001
n_enc_dec_layers:
  value: 1
optimizer:
  value: Nadam
