wandb_version: 1

Cell_Type:
  value: RNN
batch_size:
  value: 32
beam_size:
  value: 1
dropout:
  value: 0.2
embedding_size:
  value: 32
epochs:
  value: 10
hidden_layer_size:
  value: 32
l_rate:
  value: 0.001
n_enc_dec_layers:
  value: 1
optimizer:
  value: Nadam
