wandb_version: 1

Cell_Type:
  value: GRU
batch_size:
  value: 64
beam_size:
  value: 10
dropout:
  value: 0.2
embedding_size:
  value: 32
epochs:
  value: 5
hidden_layer_size:
  value: 32
l_rate:
  value: 0.01
n_enc_dec_layers:
  value: 3
optimizer:
  value: Nadam
