wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.22
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.5
    t:
      1:
      - 5
      4: 3.7.5
      5: 0.10.22
      8:
      - 5
activation:
  desc: null
  value: tanh
batch_size:
  desc: null
  value: 32
epochs:
  desc: null
  value: 5
hlayer_size:
  desc: null
  value: 32
initializer:
  desc: null
  value: random
l_rate:
  desc: null
  value: 0.0001
loss:
  desc: null
  value: cross_entropy
n_hlayers:
  desc: null
  value: 4
optimizer:
  desc: null
  value: sgd
