wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 16
epochs:
  value: 5
hlayer_size:
  value: 128
initializer:
  value: xavier
l_rate:
  value: 0.001
loss:
  value: squared_error
n_hlayers:
  value: 3
optimizer:
  value: nag
