wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 32
epochs:
  value: 10
hlayer_size:
  value: 128
initializer:
  value: xavier
l_rate:
  value: 0.0001
loss:
  value: squared_error
n_hlayers:
  value: 4
optimizer:
  value: rmsprop
