wandb_version: 1

activation:
  value: relu
batch_size:
  value: 32
epochs:
  value: 5
hlayer_size:
  value: 128
initializer:
  value: random
l_rate:
  value: 0.001
loss:
  value: cross_entropy
n_hlayers:
  value: 5
optimizer:
  value: nadam
