wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 32
epochs:
  value: 10
hlayer_size:
  value: 32
initializer:
  value: random
l_rate:
  value: 0.0001
loss:
  value: cross_entropy
n_hlayers:
  value: 5
optimizer:
  value: mgd
