wandb_version: 1

activation:
  value: relu
batch_size:
  value: 64
epochs:
  value: 10
hlayer_size:
  value: 32
initializer:
  value: xavier
l_rate:
  value: 0.0001
loss:
  value: cross_entropy
n_hlayers:
  value: 4
optimizer:
  value: nadam
