wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 16
epochs:
  value: 10
hlayer_size:
  value: 128
initializer:
  value: random
l_rate:
  value: 0.001
loss:
  value: squared_error
n_hlayers:
  value: 5
optimizer:
  value: nadam
