wandb_version: 1

activation:
  value: relu
batch_size:
  value: 32
epochs:
  value: 5
hlayer_size:
  value: 32
initializer:
  value: random
l_rate:
  value: 0.0001
loss:
  value: squared_error
n_hlayers:
  value: 5
optimizer:
  value: rmsprop
