wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 16
epochs:
  value: 5
hlayer_size:
  value: 128
initializer:
  value: xavier
l_rate:
  value: 0.0001
loss:
  value: cross_entropy
n_hlayers:
  value: 3
optimizer:
  value: sgd
