wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 64
epochs:
  value: 5
hlayer_size:
  value: 64
initializer:
  value: random
l_rate:
  value: 0.001
loss:
  value: cross_entropy
n_hlayers:
  value: 3
optimizer:
  value: mgd
