wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 32
epochs:
  value: 5
hlayer_size:
  value: 128
initializer:
  value: xavier
l_rate:
  value: 0.001
loss:
  value: squared_error
n_hlayers:
  value: 5
optimizer:
  value: sgd
