wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 16
epochs:
  value: 5
hlayer_size:
  value: 32
initializer:
  value: random
l_rate:
  value: 0.0001
loss:
  value: squared_error
n_hlayers:
  value: 4
optimizer:
  value: nag
