wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.21
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.5
    t:
      1:
      - 2
      - 3
      - 5
      4: 3.7.5
      5: 0.10.21
      8:
      - 5
batch_size:
  desc: null
  value: 100
learning_rate:
  desc: null
  value: 0.0001
no_of_epochs:
  desc: null
  value: 50
