wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 16
epochs:
  value: 10
hlayer_size:
  value: 32
initializer:
  value: xavier
l_rate:
  value: 0.001
loss:
  value: cross_entropy
n_hlayers:
  value: 5
optimizer:
  value: adam
